# Generated by Django 3.2.10 on 2021-12-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_rename_product_variation_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='product_name',
            new_name='product',
        ),
    ]
