# Generated by Django 3.2.10 on 2021-12-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='account',
            new_name='user',
        ),
    ]
