# Generated by Django 3.2.10 on 2021-12-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_rename_product_name_variation_product'),
        ('carts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store_app.Variation'),
        ),
    ]
